### ISSUE TITLE
Broken build for ARM64

### ISSUE THREAD

**Issue by Mikchel** [clockley/watchdogd#1]
(general) st@typhoon-linux:/.2/Eric/Variscite/watchdogd-4.1.4$ LANG=posix aarch64-fslc-linux-g++ --version
aarch64-fslc-linux-g++ (GCC) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(general) st@typhoon-linux:/.2/Eric/Variscite/watchdogd-4.1.4$ LANG=posix make V:=1
aarch64-fslc-linux-g++ -DHAVE_CONFIG_H -I. -I./src   -I/opt/fslqt5_sdk/sysroots/aarch64-fslc-linux/usr/include -fPIC -pthread --sysroot=/opt/fslqt5_sdk/sysroots/aarch64-fslc-linux -fdebug-prefix-map=/.2/Eric/Variscite/watchdogd-4.1.4=. -c -o src/threads.o src/threads.cpp
src/threads.cpp: In function 'void* TestDirThread(void*)':
src/threads.cpp:337:11: error: 'SYS_select' was not declared in this scope; did you mean 'SYS_pselect6'?
  337 |   syscall(SYS_select, 0, NULL, NULL, NULL, &tv);
      |           ^~~~~~~~~~
      |           SYS_pselect6
Makefile:611: recipe for target 'src/threads.o' failed
make: *** [src/threads.o] Error 1

**Comment by clockley** [comment]
Hi @Mikchel,

Thanks for the report, I'll try to reproduce this issue and create a patch by the weekend :)

**Comment by clockley** [comment]
Please try building with the latest commit

**Comment by Mikchel** [comment]
I did this define manually in cpp file. So app was built but with cheats :)
Ok. Today i will try that commit
Thanks
WBR,

Christian Lockley ***@***.***> 5 октября 2021 г. 05:26:09 
написал:

**Comment by clockley** [comment]
Please apply the following patch in addition to the first one:

`diff --git a/src/threads.cpp b/src/threads.cpp
index 5db21c4..9acf9f5 100644
--- a/src/threads.cpp
+++ b/src/threads.cpp
@@ -323,21 +323,21 @@ static void *TestDirThread(void *arg)
        tv.tv_sec = 30;
 
        for (;;) {
                if (ExecuteRepairScripts() < 0) {
                        s->error |= SCRIPTFAILED;
                } else {
                        if (s->error & SCRIPTFAILED) {
                                s->error &= !SCRIPTFAILED;
                        }
                }
-
+               tv.tv_sec = 30;
                syscall(SYS_pselect6, 0, NULL, NULL, NULL, &tv);
 
                if (stop == 1) {
                        pthread_exit(NULL);
                }
        }
 
        return NULL;
 }`

**Comment by clockley** [comment]
If everything looks good I'll close this issue in a few days, feel free to contact me if you have any questions/bug reports on this software

**Comment by clockley** [comment]
> I did this define manually in cpp file. So app was built but with cheats :) Ok. Today i will try that commit Thanks WBR, Christian Lockley ***@***.***> 5 октября 2021 г. 05:26:09 написал:
> […](#)
> Please try building with the latest commit — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Also, could you post the define? The define may be a better way to solve this. Thanks!

**Comment by Mikchel** [comment]
Yes, it compiled ok. Thanks.
